ALTER TABLE vouchers ADD COLUMN uses_allowed INTEGER NOT NULL DEFAULT 1;
ALTER TABLE vouchers ADD COLUMN use_count INTEGER NOT NULL DEFAULT 0;

UPDATE vouchers SET use_count = 1 WHERE used_at IS NOT NULL;
